options:
  license-manager-backend-base-url:
    type: string
    default:
    description: |
      The license-manager backend url.
  log-level:
    type: string
    default: INFO
    description: |
      Acceptable values; DEBUG, INFO, ERROR, WARNING, CRITICAL.
  stat-interval:
    type: int
    default: 300
    description: |
      Interval (in seconds) at which the reconcile cron will run.
  timeout-interval:
    type: int
    default: 30
    description: |
      Interval (in seconds) at which the agent service will be killed if not finished.
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL with the protocol, e.g. `https://pypicloud.example.com`.
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME.
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD in plain text.
  sentry-dsn:
    type: string
    default: ""
    description: |
      Sentry DSN url.
  lmutil-path:
    type: string
    default:
    description: |
      Path to the lmutil binary. Leave blank if not needed.
  rlmutil-path:
    type: string
    default:
    description: |
      Path to the rlmutil binary. Leave blank if not needed.
  lsdyna-path:
    type: string
    default:
    description: |
      Path to the LS-Dyna binary. Leave blank if not needed.
  lmxendutil-path:
    type: string
    default:
    description: |
      Path to the LM-X binary. Leave blank if not needed.
  use-reconcile-in-prolog-epilog:
    type: boolean
    default: True
    description: |
      Flags if reconciliation should be triggered when running Prolog/Epilog scripts. Defaults to true.
  auth0-domain:
    type: string
    default:
    description: |
      Domain for the Auth0 API where auth tokens will be fetched.
  auth0-audience:
    type: string
    default:
    description: |
      Audience for the Auth0 issued tokens.
  auth0-client-id:
    type: string
    default:
    description: |
      The ID for the Auth0 app client to which tokens will be issued.
  auth0-client-secret:
    type: string
    default:
    description: |
      The secret key for the Auth0 app client to which tokens will be issued.
  deploy-env:
    type: string
    default: STAGING
    description: |
      The deployment stage, e.g. PROD, STAGING, LOCAL
