options:
  license-manager-backend-base-url:
    type: string
    default:
    description: |
      The license-manager backend url.
  log-level:
    type: string
    default: INFO
    description: |
      Acceptable values; DEBUG, INFO, ERROR, WARNING, CRITICAL.
  stat-interval:
    type: int
    default: 300
    description: |
      Interval (in seconds) at which the reconcile cron will run.
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL with the protocol, e.g. `https://pypicloud.example.com`.
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME.
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD in plain text.
  sentry-dsn:
    type: string
    default:
    description: |
      Sentry DSN url.
  lmutil-path:
    type: string
    default:
    description: |
      Path to the lmutil binary. Leave blank if not needed.
  rlmutil-path:
    type: string
    default:
    description: |
      Path to the rlmutil binary. Leave blank if not needed.
  lsdyna-path:
    type: string
    default:
    description: |
      Path to the LS-Dyna binary. Leave blank if not needed.
  auth0-domain:
    type: string
    default:
    description: |
      Domain for the Auth0 API where auth tokens will be fetched.
  auth0-audience:
    type: string
    default:
    description: |
      Audience for the Auth0 issued tokens.
  auth0-client-id:
    type: string
    default:
    description: |
      The ID for the Auth0 app client to which tokens will be issued.
  auth0-client-secret:
    type: string
    default:
    description: |
      The secret key for the Auth0 app client to which tokens will be issued.
