options:
  jwt-key:
    type: string
    default:
    description: |
      JWT to access the backend with.
  license-manager-backend-base-url:
    type: string
    default:
    description: |
      The license-manager backend url.
  log-level:
    type: string
    default: INFO
    description: |
      Acceptable values; DEBUG, INFO, ERROR, WARNING, CRITICAL.
  stat-interval:
    type: int
    default: 300
    description: |
      Interval (in seconds) at which the reconcile cron will run.
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL with the protocol, e.g. `https://pypicloud.example.com`.
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME.
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD in plain text.
  sentry-dsn:
    type: string
    default:
    description: |
      Sentry DSN url.
  lmutil-path:
    type: string
    default:
    description: |
      Path to the lmutil binary. Leave blank if not needed.
  rlmutil-path:
    type: string
    default:
    description: |
      Path to the rlmutil binary. Leave blank if not needed.
