options:
  # Resource URL
  backend-base-url:
    type: string
    default:
    description: |
      The License Manager API URL

  # Slurm related setings
  scontrol-path:
    type: string
    default: "/usr/bin/scontrol"
    description: |
      Absolute path to the scontrol command
  sacctmgr-path:
    type: string
    default: "/usr/bin/sacctmgr"
    description: |
      Absolute path to the sacctmgr command
  squeue-path:
    type: string
    default: "/usr/bin/squeue"
    description: |
      Absolute path to the squeue command

  # License Manager Agent settings
  stat-interval:
    type: int
    default: 300
    description: |
      Interval (in seconds) at which the reconciliation process should run
  lmutil-path:
    type: string
    default:
    description: |
      Path to the FlexLM binary. Leave blank if not needed.
  rlmutil-path:
    type: string
    default:
    description: |
      Path to the RLM binary. Leave blank if not needed.
  lsdyna-path:
    type: string
    default:
    description: |
      Path to the LS-Dyna binary. Leave blank if not needed.
  lmxendutil-path:
    type: string
    default:
    description: |
      Path to the LM-X binary. Leave blank if not needed.
  olixtool-path:
    type: string
    default:
    description: |
      Path to the OLicense binary. Leave blank if not needed.
  dslicsrv-path:
    type: string
    default:
    description: |
      Path to the DSLicSrv binary. Leave blank if not needed.
  use-reconcile-in-prolog-epilog:
    type: boolean
    default: True
    description: |
      Flags if reconciliation should be triggered when running Prolog/Epilog scripts. Defaults to true.

  # Auth related settings
  oidc-domain:
    type: string
    default:
    description: |
      Domain for the OIDC provider API where auth tokens will be fetched
  oidc-client-id:
    type: string
    default:
    description: |
      The ID for the OIDC provider app client to which tokens will be issued
  oidc-client-secret:
    type: string
    default:
    description: |
      The secret key for the OIDC provider app client to which tokens will be issued


  # Other settings
  sentry-dsn:
    type: string
    default: ""
    description: |
      Sentry DSN url.
  cache-dir:
    type: string
    default: "/var/cache/license-manager"
    description: |
      Absolute path to the cache directory
  log-level:
    type: string
    default: INFO
    description: |
      Acceptable values; DEBUG, INFO, ERROR, WARNING, CRITICAL.
  deploy-env:
    type: string
    default: STAGING
    description: |
      The deployment stage, e.g. PROD, STAGING, LOCAL
